### ISSUE TITLE
Week 1st-comments

### ISSUE THREAD

**Issue by parvizi** [AndreiBaetica/Dungeoneer#10]
**Wiki comments:**
1-	The outline is not clear and needs more explanation. You can take a look at this link (https://en.wikipedia.org/wiki/Dungeoneer_(game)). For outline, I think if you quickly mention that it is a 2D game in the first sentence, readers will understand your project better. You can also upload some pictures of the game scene (if it is available) to show your meaning.
2-	The objective is vague. Is it a mobile/desktop or online game? Who is going to use the app? Focus on significant features of your application.
3-	In the architecture section, you should draw a very abstract level of your final product figure that shows how assets (components/servers/applications/DBs/...) interact together. For example, is the architecture client-server? Do you expect to use a DB? What are your stakeholders? 
4-	 - For the mentioned risks, what are possible solutions to overcome risks? This will help you to carefully monitor your project and always consider the risks and have a couple of alternative plans in advance. Also, I think features and scope creeping is not a risk. If your project scope change, it means your objective or management is wrong! Instead, there are some risks in your project that should be considered such as compatibility with various platforms(Android/Apple/..) and devices(tablet/cell phones with different resolutions) and etc. 
5-	For the initial plan, you need to setup a communication and project management tool(like GitHub and MSTeams). You should have a plan to acquire requirements alongside the technical plan that you have mentioned. For example, what is the first step to gather requirements, what sources of information/data are already available, can you interview with some stakeholders(definitely some of you/your friends/... are clients), how many transactions do you expect to receive per second/per day and etc. Then, you should search and choose required technologies. Make a simple prototype and validate your product with customers before development. Design basic features regarding highest prior requirements. Test your product and release it on the marketplace. 
6-	Good meeting minutes.
7-	Please add your project requirements.
**Issue comments:**
8-	Please make a project by clicking on ‘Projects’ close to ‘Wiki’ and make a board where you can monitor your tasks easily.

**Comment by AndreiBaetica** [comment]
All the above points have now been addressed.
