### ISSUE TITLE
Test Random Generation Algorithm Output

### ISSUE THREAD

**Issue by AndreiBaetica** [AndreiBaetica/Dungeoneer#117]
Making this as a ticket because all hands of deck are needed to make sure this is robust.

Instructions:
- Link your IDE with unity if you haven't already
- Put a breakpoint on line 32 of DungeonGenerator
- load the SampleScene scene
- Start the IDE debugger
- Start the game
- When the breakpoint is hit, validate the success criteria, and draw a map of the dungeon
- Post the map and a screenshot of the _validNeighbors contents to the Debug channel in slack

Definition of Done:
- 5 runs for each dev, record output in a grid with connections visible.

Test Success Criteria:
- No Exceptions are thrown
- In the DungeonGenerator class, the list _invalidNeighbors should be empty
- All items in the _validNeighbors list should have proper connections

**Comment by SebastienGorman** [comment]
[Run 1](https://cdn.discordapp.com/attachments/801615495794262056/846904319462342666/image.png)
[Run 2](https://cdn.discordapp.com/attachments/801615495794262056/846904330410131477/image_1.png)
[Run 3](https://cdn.discordapp.com/attachments/801615495794262056/846904328639217664/image_2.png)
[Run 4](https://cdn.discordapp.com/attachments/801615495794262056/846904325489557524/image_3.png)
[Run 5](https://cdn.discordapp.com/attachments/801615495794262056/846904320732823582/image_4.png)

**Comment by chern042** [comment]
[Test 1](https://cdn.discordapp.com/attachments/801615495794262056/847552652115968111/Test_1of5Gridded.png)
[Test 2](https://cdn.discordapp.com/attachments/801615495794262056/847552656972316672/Test_2of5Gridded.png)
[Test 3](https://cdn.discordapp.com/attachments/801615495794262056/847552659622723584/Test_3of5Gridded.png)
[Test 4](https://cdn.discordapp.com/attachments/801615495794262056/847552661939290222/Test_4of5Gridded.png)
[Test 5](https://cdn.discordapp.com/attachments/801615495794262056/847552662839885824/Test_5of5Gridded.png)
