### ISSUE TITLE
SPIKE: Investigate how sound works in game design.

### ISSUE THREAD

**Issue by AndreiBaetica** [AndreiBaetica/Dungeoneer#145]
DoD:

- Investigate the feasibility of purchasing/using free sounds from the asset store vs. making our own
- Investigate sounds played by UI interactions
- Investigate sounds from the game world (footsteps, ambient, attacks etc.)
- Investigate how soundtracks work

**Comment by RossBaumgartner** [comment]
Deemed out of scope for our demo release
