### ISSUE TITLE
Week 2nd: comments

### ISSUE THREAD

**Issue by parvizi** [AndreiBaetica/Dungeoneer#15]
Thanks for considering my previous comments. I have some more comments:
1- Improve your meeting minutes by adding some more information such as:
  g)	Who are in the meeting
  h)	What issues were discussed
  i)	What decisions did you get
2- Tasks have been assigned to only two members!

**Comment by AndreiBaetica** [comment]
All comments have been addressed. Earlier meeting minutes have been updated to reflect these requirements.
