### ISSUE TITLE
Enemy Not dying bug

### ISSUE THREAD

**Issue by RossBaumgartner** [AndreiBaetica/Dungeoneer#199]
The second enemy in the sample scene does not die, this might indicate a bug in the enemy controller when multiple enemies are present

**Comment by AndreiBaetica** [comment]
Some notes: When trying to kill multiple people in the test dungeon, the nullpointer does get thrown but the second and subsequent enemies are still killable.

This bug also wasn't present during summer, so likely something got unassigned in the prefab that's causing this.
