### ISSUE TITLE
Showing an attack preview on the grid

### ISSUE THREAD

**Issue by RossBaumgartner** [AndreiBaetica/Dungeoneer#27]
The player must be able to see the area a spell is cast, a slash will hit, etc.

Once the player selects to preview an attack (this can be just a button for testing)
* check to see where the attack can hit (wall detection)
* dyamically determine how big or what size the attack is
* area of affect is hightlighted on grid system based on the players facing direction
* be able to go back to the regular grid system (if player no longer wishes to use attack)

**Comment by AndreiBaetica** [comment]
duplicate
