### ISSUE TITLE
Spike: Prototype Positioning of UI Elements

### ISSUE THREAD

**Issue by SebastienGorman** [AndreiBaetica/Dungeoneer#36]
We need to figure out where our UI elements will sit on the screen for maximal usability and minimal interference with gameplay.

Dod:

- Efficient prototype of UI layout
- Scalable with varying screen resolution and aspect ratio

**Comment by AndreiBaetica** [comment]
@SebastienGorman do we still need this ticket or can we close it?

**Comment by SebastienGorman** [comment]
done
