### ISSUE TITLE
Adding Minimap Sprite

### ISSUE THREAD

**Issue by SebastienGorman** [AndreiBaetica/Dungeoneer#37]
Will need to create a grid of sprites and update it according to what it going on in the game. Think of it as a mini Minesweeper. Each element on the grid will be either "No terrain", "Undiscovered Terrain" or "Discovered Terrain". We can also add special sprites for ladder rooms, key rooms, starting room, etc. in the future.

**Comment by AndreiBaetica** [comment]
dropping in favour of zoomed out view
